# Generated by Django 5.0.4 on 2024-08-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsolution', '0002_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_img',
            field=models.ImageField(upload_to='project_img'),
        ),
    ]
